name: build

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - 'Docs/**'       # Docs folder in root of repo
      - '**/*.md'       # .md files anywhere in the repo
      - '**/LICENSE'    # LICENSE files anywhere in the repo
      - '**/.gitignore' # .gitignore files anywhere in the repo
      
  pull_request:
    branches: [main]
    paths-ignore:
      - 'Docs/**'       # Docs folder in root of repo
      - '**/*.md'       # .md files anywhere in the repo
      - '**/LICENSE'    # LICENSE files anywhere in the repo
      - '**/.gitignore' # .gitignore files anywhere in the repo
      
  workflow_dispatch:
    
  schedule:
    - cron: '16 9 * * *' # once a day @ 9:16am UTC (2:16am PST)
    
jobs:
  macOS-13:
    name: macOS 13 Ventura
    runs-on: macos-13
    steps:
    - uses: actions/checkout@main
    - name: Build
      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "generic/platform=macOS,name=Any Mac"
    # - name: Unit Tests
    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "platform=macOS"

  macCatalyst:
    name: macCatalyst
    runs-on: macos-13
    steps:
    - uses: actions/checkout@main
    - name: Build
      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "generic/platform=macOS,variant=Mac Catalyst,name=Any Mac"
    # - name: Unit Tests
    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "platform=macOS,variant=Mac Catalyst"

  iOS:
    name: iOS
    runs-on: macos-13 # this must be macos, GitHub does not offer iOS directly but we can use xcodebuild
    steps:
    - uses: actions/checkout@main
    - name: iPhone 15 Simulator - Build
      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "generic/platform=iOS Simulator,name=Any iOS Device"
    # - name: iPhone 15 Simulator - Unit Tests
    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "platform=iOS Simulator,name=iPhone 15"

  tvOS:
    name: tvOS
    runs-on: macos-13 # this must be macos, GitHub does not offer tvOS directly but we can use xcodebuild
    steps:
    - uses: actions/checkout@main
    - name: Apple TV - Build
      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "generic/platform=tvOS Simulator,name=Any tvOS Simulator Device"
    # - name: Apple TV - Unit Tests
    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "platform=tvOS Simulator,name=Apple TV 4K (2nd generation)"

  watchOS:
    name: watchOS
    runs-on: macos-13 # this must be macos, GitHub does not offer watchOS directly but we can use xcodebuild
    steps:
    - uses: actions/checkout@main
    - name: Apple Watch - Build
      run: xcodebuild build -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "generic/platform=watchOS Simulator,name=Any watchOS Simulator Device"
    # - name: Apple Watch - Unit Tests
    #   run: xcodebuild test -workspace ".swiftpm/xcode/package.xcworkspace" -scheme "SwiftUIPageView-CI" -destination "platform=watchOS Simulator,name=Apple Watch Series 8 (45mm)"

  demo-iOS:
    name: Demo Project (iOS)
    runs-on: macos-13
    steps:
    - uses: actions/checkout@main
    - name: Select Xcode version
      run: sudo xcode-select -s "/Applications/Xcode_15.0.app"
    - name: Demo - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Demo/Demo.xcodeproj" -resolvePackageDependencies
    - name: Demo - Build
      run: xcodebuild build -project "Demo/Demo.xcodeproj" -scheme "Demo" -destination "platform=iOS Simulator,name=iPhone 15"

  demo-macOS:
    name: Demo Project (macOS)
    runs-on: macos-13
    steps:
    - uses: actions/checkout@main
    - name: Select Xcode version
      run: sudo xcode-select -s "/Applications/Xcode_15.0.app"
    - name: Demo - Resolve Package Dependencies # needed because sometimes xcodebuild fails otherwise
      run: xcodebuild -project "Demo/Demo.xcodeproj" -resolvePackageDependencies
    - name: Demo - Build
      run: xcodebuild build -project "Demo/Demo.xcodeproj" -scheme "Demo" -destination "generic/platform=macOS,name=Any Mac"

# xcodebuild test reference:
# https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/08-automation.html
